- simulator: CARLA
  autostart: true
  carla_host: localhost
  carla_port: 2000
  transaction_timeout: 1000
  do_step_timeout: 1000
  initialisation_timeout: 10000
  additional_parameters: "-ego hero -sr --resumeafter 5" # look up Configuration.md in Carla-OSI-Service for more options
  sensor_view_config:
  - base_name: OSMPSensor1 # Name must start with OSMP or OSI
    parent_name: hero
    sensor_type: camera
    sensor_mounting_position:
      x: -5
      y: 0
      z: 2
      roll: 0
      pitch: 0
      yaw: 0
    number_of_pixels_horizontal: 1280
    number_of_pixels_vertical: 720
    field_of_view_horizontal: 90
- simulator: OSMP
  autostart: true
  model: "ObjectBasedGenericPerceptionObjectModel.fmu"
  transaction_timeout: 5000
  do_step_timeout: 5000
  input:
    - {interface_name: "OSMPSensorView", base_name: "OSMPSensorView[0]"}
  output:
    - {interface_name: "OSMPSensorData", base_name: "OSMPSensorData[0]"}
  parameter:
    - {name: "profile" , value: "Ibeo_LUX_2010"}
- simulator: OSMP
  autostart: true
  model: "ReflectionBasedRadarModel.fmu"
  transaction_timeout: 5000
  do_step_timeout: 5000
  input:
    - {interface_name: "OSMPSensorView", base_name: "OSMPSensorView[1]"}
  output:
    - {interface_name: "OSMPSensorData", base_name: "OSMPSensorData[1]"}
- simulator: OSMP
  autostart: true
  transaction_timeout: 5000
  do_step_timeout: 5000
  input:
    - {interface_name: "OSMPSensorViewCamera", base_name: OSMPSensor1} # Sensor1 sensorview contains camera data. Each image is saved with its timestamp and given interface_name.
    - {interface_name: "OSMPSensorViewObjectIbeo_LUX_2010", base_name: "OSMPSensorView[0]"}
    - {interface_name: "OSMPSensorDataObjectIbeo_LUX_2010", base_name: "OSMPSensorData[0]"}
    - {interface_name: "OSMPSensorViewGeometricRadar", base_name: "OSMPSensorView[1]"}
    - {interface_name: "OSMPSensorDataGeometricRadar", base_name: "OSMPSensorData[1]"}
