- simulator: CARLA
  carla_host: localhost
  carla_port: 2000
  client_host: localhost
  client_port: 51425
  delta: 0.03
  transaction_timeout: 30000
  do_step_timeout: 30000
  initialisation_timeout: 60000
- simulator: OSMP #OSMP-Service
  model: /ostar/OSMPDummySensor.fmu
  prefix: "#test#"
  host: localhost
  port: 51426
  transaction_timeout: 5000
  do_step_timeout: 5000
  input:
      - {interface_name: OSMPSensorView, base_name: OSMPSensorViewGroundTruth, default_value: ""}
  output:
      - {interface_name: "OSMPSensorData", base_name: OSMPSensorData, default_value: ""}
