version: '3'

services:
  osmp1:
    image: ostar:osmpservice
    ports:
      - "51424:51425"
  osmp2:
    image: ostar:osmpservice
    ports:
      - "51425:51425"
  cosima:
    image: ostar:cosima
    volumes:
     - $PWD:/ostar
    command: "./CoSimulationManager -v ostar/openloop.yaml"
    network_mode: host
